### ISSUE TITLE
Can we use ASH with an already trained model?

### ISSUE THREAD

**Issue by aqibsaeed** [andrijazz/ash#4]
Hi, 

Thanks for the code. I have a question, can I use the `ash_b(.)` function in the forward pass of a model that is already pretrained (e.g., on CIFAR-10)? or the model has to be trained with `ash_b(.)` in place?

```
class Net(nn.Module):
    ...
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.features(x)
        x = self.avgpool(x)
        
        # add activation shaping to forward pass of your network
        x = ash_b(x)
        
        x = torch.flatten(x, 1)
        x = self.classifier(x)
        return x
```

**Comment by andrijazz** [comment]
Hello ... You can use pretrained model without `ash` and just add `ash` at test time.
